// Warm sepia-toned map styles matching the Echoes cream/brown/amber palette

export const MAP_STYLE_LIGHT = [
    { elementType: 'geometry', stylers: [{ color: '#f0e6d3' }] },
    { elementType: 'labels.text.stroke', stylers: [{ color: '#f5ede0' }] },
    { elementType: 'labels.text.fill', stylers: [{ color: '#7a5c3a' }] },
    { featureType: 'landscape', elementType: 'geometry', stylers: [{ color: '#ede0cc' }] },
    { featureType: 'poi', elementType: 'geometry', stylers: [{ color: '#ddd4c0' }] },
    { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#8a6a48' }] },
    { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#c8d8b0' }] },
    { featureType: 'poi.park', elementType: 'labels.text.fill', stylers: [{ color: '#6a8a58' }] },
    { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#e8d5b8' }] },
    { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#d8c8a8' }] },
    { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#9a7a58' }] },
    { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#d4b888' }] },
    { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#c4a878' }] },
    { featureType: 'transit', elementType: 'geometry', stylers: [{ color: '#e0d0b8' }] },
    { featureType: 'transit.station', elementType: 'labels.text.fill', stylers: [{ color: '#8a6a48' }] },
    { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#a8c4d8' }] },
    { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#4a7a9a' }] },
    { featureType: 'administrative', elementType: 'geometry.stroke', stylers: [{ color: '#c4a87c' }] },
    { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#5a3a1a' }] },
];

export const MAP_STYLE_DARK = [
    { elementType: 'geometry', stylers: [{ color: '#1c140a' }] },
    { elementType: 'labels.text.stroke', stylers: [{ color: '#0e0a04' }] },
    { elementType: 'labels.text.fill', stylers: [{ color: '#c8a870' }] },
    { featureType: 'landscape', elementType: 'geometry', stylers: [{ color: '#150f07' }] },
    { featureType: 'poi', elementType: 'geometry', stylers: [{ color: '#1e1608' }] },
    { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#a07840' }] },
    { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#0e1a08' }] },
    { featureType: 'poi.park', elementType: 'labels.text.fill', stylers: [{ color: '#5a8040' }] },
    { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#2a1e10' }] },
    { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#1a1208' }] },
    { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#9a7840' }] },
    { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#3a2812' }] },
    { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#2a1c0a' }] },
    { featureType: 'transit', elementType: 'geometry', stylers: [{ color: '#1e1608' }] },
    { featureType: 'transit.station', elementType: 'labels.text.fill', stylers: [{ color: '#8a6030' }] },
    { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#081018' }] },
    { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#304858' }] },
    { featureType: 'administrative', elementType: 'geometry.stroke', stylers: [{ color: '#3a2810' }] },
    { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#d0a868' }] },
];
